INSERT INTO Settings VALUES ("Application:Appearance:Language", "en-US", 0)
INSERT INTO Settings VALUES ("Application:Appearance:Theme", "DarkTheme", 0)
INSERT INTO Settings VALUES ("Application:CommandResolverOptions:AutomaticResolverSelection", "true", 0)
INSERT INTO Settings VALUES ("Application:CommandResolverOptions:SelectedResolver", "Smart command resolver", 0)
INSERT INTO Settings VALUES ("Application:ChatGPT:Gemini:ServiceApiKey", "", 1)
INSERT INTO Settings VALUES ("Application:SpeechToText:SelectedConverter", "", 1)
