<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

	<ItemGroup>
		<Compile Remove="AssemblyInfo.cs" />
	</ItemGroup>

	<ItemGroup>
		<Compile Include="AssemblyInfo.cs">
			<Link>Properties\AssemblyInfo.cs</Link>
		</Compile>
	</ItemGroup>

	<ItemGroup>
    <PackageReference Include="Synergy.WPF.Common" Version="1.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\VoiceAssistant.UI.Appearance\VoiceAssistant.UI.Appearance.csproj" />
  </ItemGroup>

</Project>
