<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ApplicationDefinition Remove="App.xaml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Synergy.WPF.Common" Version="1.0.0" />
    <PackageReference Include="Synergy.WPF.Navigation" Version="2.0.21" />
  </ItemGroup>

  <ItemGroup>
    <Page Include="App.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CSPythonInvoker\CSPythonInvoker.csproj" />
    <ProjectReference Include="..\Plugin.Registrator\Plugin.Registrator.csproj" />
    <ProjectReference Include="..\VoiceAssistant.ChatGPT\VoiceAssistant.ChatGPT.csproj" />
    <ProjectReference Include="..\VoiceAssistant.Recording\VoiceAssistant.Recording.csproj" />
    <ProjectReference Include="..\VoiceAssistant.Services\VoiceAssistant.Services.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Views\" />
  </ItemGroup>

</Project>
