<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AllowUnsafeBlocks>False</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ApplicationDefinition Remove="App.xaml" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="AssemblyInfo.cs" />
  </ItemGroup>

  <ItemGroup>
	  <Compile Include="AssemblyInfo.cs">
		  <Link>Properties\AssemblyInfo.cs</Link>
	  </Compile>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.122" />
    <PackageReference Include="Synergy.WPF.Common" Version="1.5.0" />
    <PackageReference Include="Synergy.WPF.Navigation" Version="3.0.2" />
  </ItemGroup>

  <ItemGroup>
    <Page Include="App.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DBConfiguration\DBConfiguration.csproj" />
    <ProjectReference Include="..\Plugins.System\Plugins.System.csproj" />
    <ProjectReference Include="..\VoiceAssistant.CommandResolving\VoiceAssistant.CommandResolving.csproj" />
    <ProjectReference Include="..\VoiceAssistant.ChatGPT\VoiceAssistant.ChatGPT.csproj" />
    <ProjectReference Include="..\VoiceAssistant.DAL\VoiceAssistant.DAL.csproj" />
    <ProjectReference Include="..\VoiceAssistant.Recording\VoiceAssistant.Recording.csproj" />
    <ProjectReference Include="..\VoiceAssistant.Scripts.Compilation\VoiceAssistant.Scripts.Compilation.csproj" />
    <ProjectReference Include="..\VoiceAssistant.Scripts.Definitions\VoiceAssistant.Scripts.Definitions.csproj" />
    <ProjectReference Include="..\VoiceAssistant.Services\VoiceAssistant.Services.csproj" />
    <ProjectReference Include="..\VoiceAssistant.SpeechSynthesis\VoiceAssistant.SpeechSynthesis.csproj" />
    <ProjectReference Include="..\VoiceAssistant.UI.Appearance\VoiceAssistant.UI.Appearance.csproj" />
    <ProjectReference Include="..\VoiceAssistant.UI.Common\VoiceAssistant.UI.Common.csproj" />
    <ProjectReference Include="..\VoiceAssistant.UI.Resources\VoiceAssistant.UI.Resources.csproj" />
    <ProjectReference Include="..\VoiceAssistant.UI.Styles\VoiceAssistant.UI.Styles.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
