<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	  <EnableDynamicLoading>true</EnableDynamicLoading>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="DefaultConfig.json" />
    <None Remove="Resources\vkontakte64.png" />
  </ItemGroup>

  <ItemGroup>
	  <EmbeddedResource Include="DefaultConfig.json"/>
    <EmbeddedResource Include="Resources\vkontakte64.png" />
  </ItemGroup>

  <ItemGroup>
	  <!--<ProjectReference Include="..\Plugin.Base\Plugin.Base.csproj">
		  <Private>false</Private>
		  <ExcludeAssets>runtime</ExcludeAssets>
	  </ProjectReference>-->
	  <ProjectReference Include="..\Plugin.S2T.Base\Plugin.S2T.Base.csproj">
		  <Private>false</Private>
		  <ExcludeAssets>runtime</ExcludeAssets>
	  </ProjectReference>
  </ItemGroup>

</Project>
